init python:
    
   GAME_PHASE_STORY = 0
   GAME_PHASE_ENCOUNTER = 1
   GAME_PHASE_INTERPRET = 2
   GAME_PHASE_CONSEQUENCE = 3
   GAME_PHASE_INTROSPECT = 4
   GAME_PHASE_RESOLUTION = 5
   GAME_PHASE_REFLECTION = 6

   BELIEF_INTENSITY_DORMANT = 0
   BELIEF_INTENSITY_SURFACE = 1
   BELIEF_INTENSITY_ACTIVE = 2
   BELIEF_INTENSITY_CORE = 3
   BELIEF_INTENSITY_EXAMINED = 4
   BELIEF_INTENSITY_RESOLVED = 5